services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./database:/var/lib/mysql     
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
  wordpress:
    image: wordpress
    labels:
      - "host=wordpress"
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=secret
  filebrowser:
    image: filebrowser/filebrowser
    labels:
      - "host=filebrowser"
  traefik:
      image: traefik
      command: --configFile=/var/traefik/traefik.yaml
      volumes:
        - ./traefik.yaml:/var/traefik/traefik.yaml
        - /var/run/docker.sock:/var/run/docker.sock
        - /data/logs:/var/log
      ports:
        - "8080:80"
