services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  wordpress:
    image: traefik/wordpress
    labels:
      - "host=wordpress"
  filebrowser:
    image: filebrowser/filebrowser
    labels:
      - "host=filebrowser"
  reverse-proxy:
      image: traefik
      command: --configFile=<wherever you mounted the config file>
      volumes:
        - ./traefik.yaml:/some!place@in*the?container
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80